---
title: 'Email Usage Analysis'
author: "Sahas Duggirala"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
  pdf_document:
    toc: yes
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
library(vroom)
```




## Email usage

In this chunk, we are analysing aggregate email usage.

```{r, emailusage}
email_data <- gss %>% 
  filter(emailmin != "NA", emailhr != "NA") %>%
  mutate(email = 60 * as.numeric(emailhr) + as.numeric(emailmin))

#Prepare the data for the mean and median lines
email_information <- email_data %>% 
  summarise(mean = mean(email, na.rm = TRUE), median = median(email, na.rm = TRUE))

# geom_histogram()+
email_data %>% 
  ggplot(aes(x=email)) +
  geom_density() +
  theme_classic()+
  theme(legend.position = "bottom")+

 # add mean and median lines
  geom_vline(aes(xintercept = email_information$mean, colour = 'mean'), linetype = "dashed", size = 2)  +
  geom_vline(aes(xintercept = email_information$median, colour = 'median'), linetype = "dashed", size = 2) +
  
  # customize color of mean and median lines
  scale_color_manual(name = NULL, values = c(mean = "#F36F21", median = "#FFF200"))  +
  labs(x = "Minutes spent on email weekly", y="Number of emails sent",
       title = "How much time you really spend emailing each week") +
  theme(text=, plot.title  = element_text (size=20, colour="#7D7D7D"),
        axis.title =  element_text(size=12, colour="#002144"), axis.title.y= element_text(size=12, colour="#002144"))

```

